version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: incident-sage-db
    environment:
      POSTGRES_DB: incidentsage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - incident-sage-network

  # Go Backend with Live Reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: incident-sage-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/incidentsage?sslmode=disable
      JWT_SECRET: your-secret-key-change-in-production
      CORS_ORIGIN: http://localhost:3000
      ENV: development
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - incident-sage-network

  # React Frontend with Live Reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: incident-sage-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8080/api/v1
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    networks:
      - incident-sage-network

volumes:
  postgres_data:

networks:
  incident-sage-network:
    driver: bridge 